import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from '../lib/utils'
import Providers from "../components/Providers";



const inter = Inter({ subsets: ["latin"] });
import  Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <Providers>
      <body className={cn('min-height-screen font-sans antialiased grainy', inter.className)}>
        <Navbar />
        {children}
      </body>
      </Providers>
    </html>
  );
}
